[package]
name = "acl_practice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
proconio = { version = "0.4.3", features = ["derive"] }
itertools = "0.10.5"
