[package]
name = "abc132"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modint = { version = "0.1.0", path = "../../tayu-procon/modint" }
proconio = "0.4.5"
